name: CI

on:
  workflow_call:
    inputs:
      private:
        default: true
        required: false
        type: boolean
    secrets:
      PLATFORMIO_AUTH_TOKEN:
        required: true

jobs:
  CI:
    uses: Arvernus/PlatformIOGithubActions/.github/workflows/iRockLibCI.yaml@main
    with:
      private: ${{ inputs.private }}
    secrets:
      PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
